[package]
name = "ambiente-cli"
description = "Command-line interface for Ambiente"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "ambiente"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
ambiente-core = { path = "../core" }
