[package]
name = "ambiente-cli"
description = "Command-line interface for Ambiente"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "ambiente"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
ambiente-core = { path = "../core" }
anyhow = "1"
clap = { version = "4", features = ["derive", "wrap_help"] }
clap_complete = "4"
midly = "0.5"
owo-colors = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
