import { createSignal, For, Show } from 'solid-js';

type PagefindMatch = { excerpt: string; meta?: { title?: string }; url: string };

type PagefindResult = { data: () => Promise<PagefindMatch> };

type Pagefind = { search: (query: string) => Promise<{ results: PagefindResult[] }> };

const pagefindPath = '/pagefind/pagefind.js';
let pagefind: Promise<Pagefind> | undefined;

function getPagefind(): Promise<Pagefind> {
	pagefind ??= import(/* @vite-ignore */ pagefindPath) as Promise<Pagefind>;
	return pagefind;
}

/** Searches the static documentation index generated by Pagefind. */
export function DocsSearch() {
	const [matches, setMatches] = createSignal<PagefindMatch[]>([]);
	const [message, setMessage] = createSignal('');
	let searchVersion = 0;

	async function search(query: string) {
		const version = ++searchVersion;
		const normalizedQuery = query.trim();
		if (!normalizedQuery) {
			setMatches([]);
			setMessage('');
			return;
		}

		setMessage('Searching…');
		try {
			const index = await getPagefind();
			const response = await index.search(normalizedQuery);
			const results = await Promise.all(response.results.slice(0, 6).map((result) => result.data()));
			if (version !== searchVersion) return;
			setMatches(results);
			setMessage(results.length === 0 ? `No pages match “${normalizedQuery}”.` : '');
		} catch {
			if (version !== searchVersion) return;
			setMatches([]);
			setMessage('Search is unavailable. Browse the guides below.');
		}
	}

	return (
		<div class="docs-search" role="search" data-pagefind-ignore>
			<label for="docs-search-input">Search documentation</label>
			<div class="docs-search__field">
				<span class="icon i-ri-search-line" aria-hidden="true" />
				<input
					id="docs-search-input"
					type="search"
					placeholder="Search the docs…"
					autocomplete="off"
					onInput={(event) => void search(event.currentTarget.value)}
				/>
			</div>
			<Show when={message()}>
				<p class="docs-search__message" role="status">
					{message()}
				</p>
			</Show>
			<Show when={matches().length > 0}>
				<div class="docs-search__results" aria-label="Search results">
					<For each={matches()}>
						{(match) => (
							<a href={match.url}>
								<strong>{match.meta?.title ?? 'Documentation page'}</strong>
								<span innerHTML={match.excerpt} />
							</a>
						)}
					</For>
				</div>
			</Show>
		</div>
	);
}
