import init, { AmbienteWasm, type InitInput } from '../generated/ambiente_wasm.js';

/** A serialized canonical Ambiente document. */
export type SerializedDocument = string;

/** A canonical operation interpreted by ambiente-core. */
export type DocumentOperation = Readonly<{ kind: string; payload?: unknown }>;

/** A half-open query span in one exact clock domain. */
export type EventQuery = Readonly<{ clock: 'absolute' | 'metric'; end: string; start: string }>;

/** A canonical event target. */
export type ApplicationEventTarget =
	Readonly<{ id: string; type: 'voice' }> | Readonly<{ id: string; type: 'symbolic' }>;

/** A note or named event payload independent of the audio backend. */
export type ApplicationEventKind =
	| Readonly<{ note: Readonly<{ pitch: number; velocity: number }>; type: 'note' }>
	| Readonly<{ name: string; type: 'named' }>;

/** One exact event coordinate. */
export type ApplicationTimePoint = Readonly<{ clock: 'absolute' | 'metric'; value: string }>;

/** A normalized backend-independent event returned by Rust. */
export type ApplicationEvent = Readonly<{
	kind: ApplicationEventKind;
	properties: Readonly<Record<string, unknown>>;
	source: Readonly<Record<string, unknown>>;
	span: Readonly<{ end: ApplicationTimePoint; start: ApplicationTimePoint }>;
	target: ApplicationEventTarget;
}>;

/** A user-facing diagnostic returned by the Rust boundary. */
export type ApplicationDiagnostic = Readonly<{
	code: string;
	help?: string;
	message: string;
	severity: 'error' | 'warning';
}>;

/** One backend-independent persisted parameter value. */
export type ApplicationParameterValue =
	| Readonly<{ type: 'boolean'; value: boolean }>
	| Readonly<{ type: 'integer'; value: number }>
	| Readonly<{ type: 'text'; value: string }>;

/** Playback settings for one canonical voice. */
export type ApplicationVoice = Readonly<{
	enabled: boolean;
	id: string;
	parameters: Readonly<Record<string, ApplicationParameterValue>>;
	sound: string;
}>;

/** The document state needed by current Studio and audio views. */
export type DocumentInspection = Readonly<{
	documentId: string;
	materialCount: number;
	seed: string;
	tempo: string;
	title: string;
	voiceCount: number;
	voices: readonly ApplicationVoice[];
}>;

/** The command/query API consumed by browser interfaces. */
export type AmbienteApplication = {
	apply(operation: DocumentOperation): readonly ApplicationDiagnostic[];
	inspect(): DocumentInspection;
	load(document: SerializedDocument): readonly ApplicationDiagnostic[];
	queryEvents(query: EventQuery): readonly ApplicationEvent[];
	serialize(): SerializedDocument;
	validate(): readonly ApplicationDiagnostic[];
};

let initialization: Promise<unknown> | undefined;

/** A typed wrapper over the generated low-level WebAssembly bindings. */
export class WasmApplication implements AmbienteApplication {
	private constructor(private readonly runtime: AmbienteWasm) {}

	/** Initializes the module and loads a canonical document. */
	static async create(document: SerializedDocument, module?: InitInput): Promise<WasmApplication> {
		initialization ??= module === undefined ? init() : init({ module_or_path: module });
		await initialization;
		return new WasmApplication(new AmbienteWasm(document));
	}

	/** Replaces the active document, leaving it unchanged when loading fails. */
	load(document: SerializedDocument): readonly ApplicationDiagnostic[] {
		return parseJson(this.runtime.load(document));
	}

	/** Returns canonical pretty-printed document JSON. */
	serialize(): SerializedDocument {
		return this.runtime.serialize();
	}

	/** Applies one canonical operation atomically. */
	apply(operation: DocumentOperation): readonly ApplicationDiagnostic[] {
		return parseJson(this.runtime.apply(JSON.stringify(operation)));
	}

	/** Returns all current document diagnostics. */
	validate(): readonly ApplicationDiagnostic[] {
		return parseJson(this.runtime.validate());
	}

	/** Queries normalized events generated by ambiente-core. */
	queryEvents(query: EventQuery): readonly ApplicationEvent[] {
		return parseJson(this.runtime.query_events(JSON.stringify(query)));
	}

	/** Returns the current document projection. */
	inspect(): DocumentInspection {
		return parseJson(this.runtime.inspect());
	}
}

function parseJson<T>(value: string): T {
	return JSON.parse(value) as T;
}
